[package]
name = "open-rpc-schema"
version = "0.0.1"
authors = ["me@austbot.com","fikgol <hit.cs.lijun@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
schemars = "0.8.11"
schemars_derive = "0.8.11"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"